<?xml version="1.0"?><package format="3"><name>factory_mapping_monitor</name><version>0.1.0</version><description>Factory mapping monitor</description><maintainer email="maintainer@example.invalid">Factory Mapping Maintainers</maintainer><license>MIT</license><buildtool_depend>ament_python</buildtool_depend><exec_depend>rclpy</exec_depend><exec_depend>sensor_msgs</exec_depend><exec_depend>sensor_msgs_py</exec_depend><exec_depend>launch_ros</exec_depend><export><build_type>ament_python</build_type></export></package>