#!/usr/bin/env bash
set -eo pipefail
source "$(dirname "$0")/env.sh"
export CMAKE_BUILD_PARALLEL_LEVEL="${BUILD_JOBS:-2}"
export MAKEFLAGS="-j$CMAKE_BUILD_PARALLEL_LEVEL"
CUDA_ARGS=()
if [[ -n "${CUDA_ARCHITECTURES:-}" ]]; then CUDA_ARGS=("-DCMAKE_CUDA_ARCHITECTURES=$CUDA_ARCHITECTURES"); fi
cd "$ROOT/ros2_ws"
/usr/bin/colcon build --executor sequential "$@" --cmake-args -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=/usr/bin/python3 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_WITH_MARCH_NATIVE=OFF -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DROS_EDITION=ROS2 -DDISTRO_ROS=humble -DBUILD_TESTING=OFF -DBUILD_WITH_CUDA="${USE_CUDA:-OFF}" -DBUILD_WITH_VIEWER="${BUILD_VIEWER:-OFF}" -DBUILD_WITH_OPENCV=OFF -DBUILD_WITH_CV_BRIDGE=OFF "${CUDA_ARGS[@]}"
